#!/usr/bin/env python

"""
   Just get the version of the package xml script in this directory."
"""

##############################################################################
# Imports
##############################################################################

from __future__ import print_function
import os
import xml.etree.ElementTree as ElementTree

##############################################################################
# Substitution
##############################################################################

def get_current_version():
    package_xml_path = os.path.join(os.getcwd(), 'package.xml')
    tree = ElementTree.parse(package_xml_path)
    root = tree.getroot()
    version = root.find('version').text
    return version


##############################################################################
# Main
##############################################################################

if __name__ == "__main__":
    print(get_current_version())

