#!/bin/bash

# Installs everything necessary to run the reindexing script.

sudo apt-get install python-wstool python-rosinstall-generator python-catkin-pkg python-bloom ros-hydro-catkin -y
rm -rf reindex
rm -f UPDATED
mkdir reindex
cd reindex
wstool init src
cd src
wstool set rosjava_build_tools --git https://github.com/rosjava/rosjava_build_tools --version=hydro -y
# We don need to build it (see below), so easier just getting the maven repo artifact for message_generation
#wstool set rosjava_bootstrap --git https://github.com/rosjava/rosjava_bootstrap --version=hydro -y
wstool set rosjava_messages --git https://github.com/rosjava/rosjava_messages --version=hydro -y
wstool update
# Don't actually want to build it, just need the package xml's floating around.
touch rosjava_messages/CATKIN_IGNORE
cd ..
. /opt/ros/hydro/setup.bash
catkin_make
. devel/setup.bash
cd src/rosjava_messages
echo "Reindexing if necessary"
./jenkins/reindex_release_message_dependencies
if [ $? -eq 0 ]; then
    echo "\nNothing changed."
    exit 0
else
    echo "Underlying message packages updated."
    VERSION=`./jenkins/get_version`
    git commit -a -m "${VERSION}"
    git push
    git tag ${VERSION}
    git push --tags
    touch ${WORKSPACE}/UPDATED
    exit 1
fi
