#!/bin/bash

# Installs everything necessary to run the reindexing script.

sudo apt-get install python-wstool python-rosinstall-generator python-catkin-pkg ros-hydro-catkin -y
rm -rf reindex
mkdir reindex
cd reindex
wstool init src
cd src
wstool set rosjava_build_tools --git https://github.com/stonier/rosjava_build_tools -y
wstool set rosjava_messages --git https://github.com/stonier/rosjava_messages -y
wstool update
touch rosjava_messages/CATKIN_IGNORE
cd ..
. /opt/ros/hydro/setup.bash
catkin_make
. devel/setup.bash
cd src/rosjava_messages
./jenkins/reindex_release_message_dependencies
VERSION=`./jenkins/get_version`
git commit -a -m "${VERSION}"
git push
git tag ${VERSION}
git push --tags

